spring.application.name=api
server.port=8082

spring.data.mongodb.uri=YOUR_MONGODB_URI

jwt.secret=YOUR_JWT_SECRET
jwt.expiration=86400000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email

# Gemini AI
gemini.api.key=YOUR_GEMINI_API_KEY